# Generated by Django 5.2.3 on 2025-07-05 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_session_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
