# Generated by Django 5.2.3 on 2025-07-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_customuser_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nueva_solicitud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permitir_nueva',
            field=models.BooleanField(default=False),
        ),
    ]
