# Generated by Django 5.2.3 on 2025-07-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unified2Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('src_ip', models.CharField(max_length=64)),
                ('dst_ip', models.CharField(max_length=64)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=16)),
                ('signature', models.CharField(max_length=255)),
                ('classification_id', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('message', models.TextField()),
                ('sid', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Alerta de escaneo',
                'verbose_name_plural': 'Alertas de escaneo',
            },
        ),
    ]
