# Generated by Django 5.2.3 on 2025-07-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnortAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=10)),
                ('signature', models.TextField()),
                ('classification_id', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=1)),
                ('message', models.TextField()),
                ('sid', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Unified2Alert',
        ),
    ]
