# Generated by Django 5.2.3 on 2025-07-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0002_snortalert_delete_unified2alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SnortAlert',
        ),
    ]
